// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClG1798bfPSWqdN-K8uisvy3dWoE8aMg0',
    appId: '1:322651006056:web:3411f9e5babc5cbfb987dd',
    messagingSenderId: '322651006056',
    projectId: 'trade-twice',
    authDomain: 'trade-twice.firebaseapp.com',
    storageBucket: 'trade-twice.firebasestorage.app',
    measurementId: 'G-F6JVRCTNQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5pmD31NwLuDs8QdN46u8lAzQxoPPwCt4',
    appId: '1:322651006056:android:5043b030ec76ce1ab987dd',
    messagingSenderId: '322651006056',
    projectId: 'trade-twice',
    storageBucket: 'trade-twice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfW3M5QlvrDhZZenXYVSaP-mure8EwEAg',
    appId: '1:322651006056:ios:579750fe87270acab987dd',
    messagingSenderId: '322651006056',
    projectId: 'trade-twice',
    storageBucket: 'trade-twice.firebasestorage.app',
    iosBundleId: 'com.example.tradeTwice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfW3M5QlvrDhZZenXYVSaP-mure8EwEAg',
    appId: '1:322651006056:ios:579750fe87270acab987dd',
    messagingSenderId: '322651006056',
    projectId: 'trade-twice',
    storageBucket: 'trade-twice.firebasestorage.app',
    iosBundleId: 'com.example.tradeTwice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClG1798bfPSWqdN-K8uisvy3dWoE8aMg0',
    appId: '1:322651006056:web:c64ad6f5ff5462efb987dd',
    messagingSenderId: '322651006056',
    projectId: 'trade-twice',
    authDomain: 'trade-twice.firebaseapp.com',
    storageBucket: 'trade-twice.firebasestorage.app',
    measurementId: 'G-Z4XDDTE3D3',
  );
}
